# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 6562ff1
_src_path: gh:makukha/copython
author_email: m.makukha@gmail.com
author_name: Michael Makukha
copyright_year: 2025
docs: github_readme
docs_url: https://github.com/makukha/shurl#readme
github_slug: makukha/shurl
github_url: https://github.com/makukha/shurl
module_name: shurl
openssf_bp_id: '10749'
project_name: shurl
project_version: 0.0.0
pypi_package_name: shurl
pypi_url: https://pypi.org/project/shurl
python_version: 3.13.5
python_version_minor: '3.13'
