unbind C-b
set-option -g prefix C-a

bind-key C-a send-prefix
bind-key r respawn-pane

set -g mouse on

set -g history-limit 10000

set -g base-index 1
set -g pane-base-index 1
set-window-option -g remain-on-exit on

set -g status-bg '#deb888'
set -g status-fg black
