services:
  # distribution images

  shurl-nginx-cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: shurl-nginx-cli
    image: docker.io/makukha/shurl:nginx-cli

  # testing services

  test-shurl-nginx-cli:
    image: docker.io/makukha/shurl:nginx-cli

    healthcheck:
      test: ["CMD-SHELL", "pidof nginx || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "8080:80"
