services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

  nginx:
    image: docker.io/makukha/shurl:nginx
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    healthcheck:
      test: ["CMD-SHELL", "pidof nginx || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    volumes:
      - ./tests/examples/nginx/projects:/opt/shurl/projects
      - ./tests/examples/nginx/workspace.toml:/opt/shurl/workspace.toml
      - ./.tmp/ssl/example.com/cert.pem:/ssl/example.com/cert.pem
      - ./.tmp/ssl/example.com/key.pem:/ssl/example.com/key.pem
